language: java
jdk:
  - oraclejdk8
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
before_script:
  - cd ui
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install
  - ./node_modules/protractor/bin/webdriver-manager update --standalone
script:
  - mvn install -DskipTests
  - cd ../server
  - ln -s ../ui/webapp webapp
  - mvn clean test jacoco:report coveralls:report
  - mvn exec:java &
  - sleep 60
  - cd ../ui
  - bower install
  - grunt
  - ./node_modules/protractor/bin/protractor src/test/js/orchidae.conf.js
